import type {
  DashboardSummary,
  DailySalesUnitProfit,
} from "@patima/shared";
import { DEFAULT_DELIVERY_UNIT_COST } from "@patima/shared";
import type {
  AdPreviewRowItem,
  AdPreviewSummary,
  AdUploadListItem,
  CampaignCostListItem,
  CampaignMappingRuleListItem,
  CostSettingListItem,
  CredentialSummary,
  OperationDetail,
  OperationListItem,
  OrderListItem,
  OrderSourceSignatureListItem,
  ProfitDetailPreview,
  SalesUnitListItem,
  StoreListItem,
  UnmappedSummary,
} from "@/lib/api/types";

export const MOCK_SELECTED_DATE = "2026-04-02";
export const MOCK_DATE_FROM = "2026-03-27";
export const MOCK_DATE_TO = "2026-04-02";

export const mockStores: StoreListItem[] = [
  {
    id: "store-main",
    name: "메인 스마트스토어",
    platformType: "NAVER_SMARTSTORE",
    sellerAccountId: "123456",
    channelNo: "999999",
    isPrimary: true,
    isActive: true,
    lastOrderSyncAt: "2026-04-02T10:01:12+09:00",
    lastOrderSyncStatus: "SUCCEEDED",
    credentialConnectionStatus: "SUCCEEDED",
    lastCredentialTestAt: "2026-04-01T10:00:00+09:00",
    memo: "대표 시연용 스토어",
    deliveryUnitCost: DEFAULT_DELIVERY_UNIT_COST,
  },
];

export const mockCredential: CredentialSummary = {
  credentialId: "credential-main",
  storeId: "store-main",
  maskedClientId: "naver-cl****",
  accessType: "SELLER",
  secretStored: true,
  credentialConnectionStatus: "SUCCEEDED",
  lastCredentialTestAt: "2026-04-01T10:00:00+09:00",
};

export const mockSalesUnits = [
  {
    id: "sales-unit-1",
    storeId: "store-main",
    standardProductName: "러닝모자",
    standardOptionName: "블랙",
    displayName: "러닝모자 / 블랙",
    memo: "주문 원본 블랙 묶음",
    isActive: true,
    deactivatedAt: null,
  },
  {
    id: "sales-unit-2",
    storeId: "store-main",
    standardProductName: "두줄 무릎 보호대",
    standardOptionName: "모던그레이",
    displayName: "두줄 무릎 보호대 / 모던그레이",
    memo: "대표 SKU",
    isActive: true,
    deactivatedAt: null,
  },
  {
    id: "sales-unit-3",
    storeId: "store-main",
    standardProductName: "트레이닝 양말",
    standardOptionName: "화이트",
    displayName: "트레이닝 양말 / 화이트",
    memo: "비용 미설정 예시",
    isActive: true,
    deactivatedAt: null,
  },
] as unknown as SalesUnitListItem[];

export const mockOrderItems: OrderListItem[] = [
  {
    id: "order-item-1",
    orderRecordId: "order-1",
    externalOrderId: "202604020001",
    orderSourceSignatureId: "signature-1",
    canonicalSalesUnitId: "sales-unit-1",
    rawProductName: "러닝모자",
    rawOptionInfo: "[함께배송] 블랙",
    sourceSignature: "러닝모자 || [함께배송] 블랙",
    displayName: "러닝모자 / 블랙",
    quantity: 2,
    productPaymentAmount: 39800,
    packageNumber: "PACKAGE-001",
    deliveryFeeAmount: 3000,
    paymentCommission: 320,
    knowledgeShoppingSellingInterlockCommission: 180,
    saleCommission: 0,
    channelCommission: 0,
    paymentDate: "2026-04-02",
    orderStatus: "DELIVERED",
    saleStatus: "SALE",
    mappingStatus: "MAPPED",
  },
  {
    id: "order-item-2",
    orderRecordId: "order-2",
    externalOrderId: "202604020014",
    orderSourceSignatureId: "signature-2",
    canonicalSalesUnitId: "sales-unit-2",
    rawProductName: "두줄 무릎 보호대",
    rawOptionInfo: "모던그레이 / 프리",
    sourceSignature: "두줄 무릎 보호대 || 모던그레이 / 프리",
    displayName: "두줄 무릎 보호대 / 모던그레이",
    quantity: 1,
    productPaymentAmount: 25900,
    packageNumber: "PACKAGE-014",
    deliveryFeeAmount: 0,
    paymentCommission: null,
    knowledgeShoppingSellingInterlockCommission: null,
    saleCommission: 0,
    channelCommission: 0,
    paymentDate: "2026-04-02",
    orderStatus: "PURCHASE_DECIDED",
    saleStatus: "SALE",
    mappingStatus: "MAPPED",
  },
  {
    id: "order-item-3",
    orderRecordId: "order-3",
    externalOrderId: "202604020021",
    orderSourceSignatureId: "signature-3",
    canonicalSalesUnitId: null,
    rawProductName: "브랜드 티셔츠",
    rawOptionInfo: "오프화이트 / M",
    sourceSignature: "브랜드 티셔츠 || 오프화이트 / M",
    displayName: null,
    quantity: 1,
    productPaymentAmount: 19900,
    packageNumber: "PACKAGE-021",
    deliveryFeeAmount: 3000,
    paymentCommission: 240,
    knowledgeShoppingSellingInterlockCommission: 140,
    saleCommission: 0,
    channelCommission: 0,
    paymentDate: "2026-04-02",
    orderStatus: "DELIVERING",
    saleStatus: "SALE",
    mappingStatus: "UNMAPPED",
  },
  {
    id: "order-item-4",
    orderRecordId: "order-4",
    externalOrderId: "202604020032",
    orderSourceSignatureId: "signature-4",
    canonicalSalesUnitId: "sales-unit-1",
    rawProductName: "러닝모자",
    rawOptionInfo: "블랙",
    sourceSignature: "러닝모자 || 블랙",
    displayName: "러닝모자 / 블랙",
    quantity: 1,
    productPaymentAmount: 19900,
    packageNumber: "PACKAGE-032",
    deliveryFeeAmount: 3000,
    paymentCommission: 0,
    knowledgeShoppingSellingInterlockCommission: 0,
    saleCommission: 0,
    channelCommission: 0,
    paymentDate: null,
    orderStatus: "CANCEL_REQUEST",
    saleStatus: "CANCEL_REQUESTED",
    mappingStatus: "MAPPED",
  },
];

export const mockSignatures: OrderSourceSignatureListItem[] = [
  {
    id: "signature-1",
    rawProductNameSnapshot: "러닝모자",
    rawOptionInfoSnapshot: "[함께배송] 블랙",
    sourceSignature: "러닝모자 || [함께배송] 블랙",
    mappingStatus: "MAPPED",
    canonicalSalesUnitId: "sales-unit-1",
    canonicalDisplayName: "러닝모자 / 블랙",
    usageCount: 18,
    externalProductId: null,
    optionCode: null,
    fallbackProductName: null,
    fallbackProductNameSource: null,
    storeSlug: null,
  },
  {
    id: "signature-2",
    rawProductNameSnapshot: "두줄 무릎 보호대",
    rawOptionInfoSnapshot: "모던그레이 / 프리",
    sourceSignature: "두줄 무릎 보호대 || 모던그레이 / 프리",
    mappingStatus: "MAPPED",
    canonicalSalesUnitId: "sales-unit-2",
    canonicalDisplayName: "두줄 무릎 보호대 / 모던그레이",
    usageCount: 9,
    externalProductId: null,
    optionCode: null,
    fallbackProductName: null,
    fallbackProductNameSource: null,
    storeSlug: null,
  },
  {
    id: "signature-3",
    rawProductNameSnapshot: "브랜드 티셔츠",
    rawOptionInfoSnapshot: "오프화이트 / M",
    sourceSignature: "브랜드 티셔츠 || 오프화이트 / M",
    mappingStatus: "UNMAPPED",
    canonicalSalesUnitId: null,
    canonicalDisplayName: null,
    usageCount: 3,
    externalProductId: null,
    optionCode: null,
    fallbackProductName: null,
    fallbackProductNameSource: null,
    storeSlug: null,
  },
];

export const mockDashboardSummary: DashboardSummary = {
  date: MOCK_SELECTED_DATE,
  totalRevenue: 1538200,
  totalProductRevenue: 1538200,
  totalDeliveryFeeAmount: 12000,
  totalAdCost: 1785440,
  roughProfit: -247240,
  estimatedNetProfit: null,
  profitStatus: "INCOMPLETE_COST",
  salesUnitCount: 8,
  incompleteCostSalesUnitCount: 1,
  unmappedOrderItemCount: 12,
  conflictOrderItemCount: 2,
  unmappedCampaignCount: 3,
  conflictCampaignCount: 1,
  intentionalUnmappedCampaignCount: 1,
  excludedOrderRevenue: 154000,
  excludedUnmappedOrderRevenue: 92000,
  excludedConflictOrderRevenue: 44000,
  excludedNonSaleOrderRevenue: 62000,
  excludedAdCost: 83200,
  excludedUnmappedAdCost: 60000,
  excludedConflictAdCost: 18000,
  excludedIntentionalUnmappedAdCost: 23200,
  totalVatAmount: 153820,
  totalVatAdjustedRevenue: 1384380,
  uniquePackageCount: 3,
  deliveryUnitCost: DEFAULT_DELIVERY_UNIT_COST,
  estimatedDeliveryBaseCost: 10500,
  customerPaidDeliveryFee: 12000,
  deliveryMargin: 1500,
};

export const mockProfits: DailySalesUnitProfit[] = [
  {
    date: MOCK_SELECTED_DATE,
    canonicalSalesUnitId: "sales-unit-1",
    displayName: "러닝모자 / 블랙",
    totalQuantity: 15,
    totalRevenue: 223500,
    totalProductRevenue: 223500,
    totalDeliveryFeeAmount: 6000,
    totalAdCost: 115432,
    totalUnitCost: 67500,
    totalFeeCost: 7822.5,
    totalOtherCost: 7500,
    roughProfit: 108068,
    estimatedNetProfit: 25245.5,
    profitStatus: "COMPLETE",
    vatAmount: 22350,
    vatAdjustedRevenue: 201150,
  },
  {
    date: MOCK_SELECTED_DATE,
    canonicalSalesUnitId: "sales-unit-2",
    displayName: "두줄 무릎 보호대 / 모던그레이",
    totalQuantity: 11,
    totalRevenue: 284900,
    totalProductRevenue: 284900,
    totalDeliveryFeeAmount: 0,
    totalAdCost: 139500,
    totalUnitCost: 110000,
    totalFeeCost: 9960,
    totalOtherCost: 4400,
    roughProfit: 145400,
    estimatedNetProfit: 21000,
    profitStatus: "COMPLETE",
    vatAmount: 28490,
    vatAdjustedRevenue: 256410,
  },
  {
    date: MOCK_SELECTED_DATE,
    canonicalSalesUnitId: "sales-unit-3",
    displayName: "트레이닝 양말 / 화이트",
    totalQuantity: 7,
    totalRevenue: 119000,
    totalProductRevenue: 119000,
    totalDeliveryFeeAmount: 6000,
    totalAdCost: 24400,
    totalUnitCost: 0,
    totalFeeCost: 0,
    totalOtherCost: 0,
    roughProfit: 94600,
    estimatedNetProfit: null,
    profitStatus: "INCOMPLETE_COST",
    vatAmount: 11900,
    vatAdjustedRevenue: 107100,
  },
];

export const mockAdCosts: CampaignCostListItem[] = [
  {
    id: "ad-cost-1",
    uploadId: "upload-1",
    reportDate: MOCK_SELECTED_DATE,
    campaignName: "0402_모바일피드_러닝모자_블랙",
    totalCost: 12039,
    canonicalSalesUnitId: "sales-unit-1",
    canonicalDisplayName: "러닝모자 / 블랙",
    mappingStatus: "MAPPED",
    mappingReason: null,
    matchedRuleCount: 1,
    reasonNote: null,
  },
  {
    id: "ad-cost-2",
    uploadId: "upload-1",
    reportDate: MOCK_SELECTED_DATE,
    campaignName: "0402_브랜드캠페인_전체",
    totalCost: 23200,
    canonicalSalesUnitId: null,
    canonicalDisplayName: null,
    mappingStatus: "UNMAPPED",
    mappingReason: "INTENTIONALLY_UNMAPPED",
    matchedRuleCount: 0,
    reasonNote: "브랜드 캠페인",
  },
  {
    id: "ad-cost-3",
    uploadId: "upload-1",
    reportDate: MOCK_SELECTED_DATE,
    campaignName: "0402_모바일피드_러닝",
    totalCost: 60000,
    canonicalSalesUnitId: null,
    canonicalDisplayName: null,
    mappingStatus: "UNMAPPED",
    mappingReason: "MULTIPLE_RULE_MATCHES",
    matchedRuleCount: 2,
    reasonNote: null,
  },
];

export const mockCampaignMappings: CampaignMappingRuleListItem[] = [
  {
    id: "mapping-1",
    storeId: "store-main",
    adChannel: "NAVER_DA",
    matchType: "CONTAINS",
    campaignPattern: "러닝모자_블랙",
    normalizedCampaignPattern: "러닝모자_블랙",
    canonicalSalesUnitId: "sales-unit-1",
    canonicalDisplayName: "러닝모자 / 블랙",
    isEnabled: true,
    disabledAt: null,
  },
  {
    id: "mapping-2",
    storeId: "store-main",
    adChannel: "NAVER_DA",
    matchType: "CONTAINS",
    campaignPattern: "무릎 보호대",
    normalizedCampaignPattern: "무릎 보호대",
    canonicalSalesUnitId: "sales-unit-2",
    canonicalDisplayName: "두줄 무릎 보호대 / 모던그레이",
    isEnabled: true,
    disabledAt: null,
  },
  {
    id: "mapping-3",
    storeId: "store-main",
    adChannel: "NAVER_DA",
    matchType: "CONTAINS",
    campaignPattern: "트레이닝 양말",
    normalizedCampaignPattern: "트레이닝 양말",
    canonicalSalesUnitId: "sales-unit-3",
    canonicalDisplayName: "트레이닝 양말 / 화이트",
    isEnabled: false,
    disabledAt: "2026-04-01T13:30:00+09:00",
  },
];

export const mockUploads: AdUploadListItem[] = [
  {
    uploadId: "upload-1",
    reportDate: MOCK_SELECTED_DATE,
    detectedWeekday: "목요일",
    weekdayValidationStatus: "PASSED",
    uploadStatus: "CONFIRMED",
    isActive: true,
    originalFileName: "2026-04-02-alpha.xlsx",
    createdAt: "2026-04-02T09:10:00+09:00",
    previewExpiresAt: null,
  },
  {
    uploadId: "upload-preview-1",
    reportDate: "2026-04-03",
    detectedWeekday: "금요일",
    weekdayValidationStatus: "PASSED",
    uploadStatus: "PREVIEW_PARSED",
    isActive: false,
    originalFileName: "2026-04-03-preview-a.xlsx",
    createdAt: "2026-04-03T09:15:00+09:00",
    previewExpiresAt: "2026-04-10T23:59:59+09:00",
  },
];

export const mockPreview: AdPreviewSummary = {
  uploadId: "upload-preview-1",
  rowCount: 27,
  reportDate: "2026-04-03",
  detectedWeekday: "금요일",
  weekdayValidationStatus: "PASSED",
  activeConfirmedUploadCount: 1,
  previewExpiresAt: "2026-04-10T23:59:59+09:00",
  previewState: "VALID",
  ruleSnapshotHash: "sha256:rule-snapshot",
  overrideSnapshotHash: "sha256:override-snapshot",
  mappingPreviewSummary: {
    mappedCount: 20,
    unmappedCount: 5,
    conflictCount: 1,
    multipleRuleMatchCount: 1,
    intentionallyUnmappedCount: 1,
  },
  requiresConfirm: true,
  status: "PREVIEW_PARSED",
};

export const mockPreviewRows: AdPreviewRowItem[] = [
  {
    rowNo: 1,
    campaignId: "cmp-1001",
    campaignName: "0403_모바일피드_러닝모자_블랙",
    adType: "성과형DA",
    adStatus: "집행중",
    weekdayLabel: "금요일",
    totalCost: 12039,
    mappingStatus: "MAPPED",
    mappingReason: null,
    displayMappingState: "MAPPED",
    matchedRuleCount: 1,
    canonicalSalesUnitId: "sales-unit-1",
    canonicalDisplayName: "러닝모자 / 블랙",
    reasonNote: null,
    reasonNoteInherited: false,
  },
  {
    rowNo: 2,
    campaignId: "cmp-1002",
    campaignName: "0403_브랜드캠페인_전체",
    adType: "성과형DA",
    adStatus: "집행중",
    weekdayLabel: "금요일",
    totalCost: 23200,
    mappingStatus: "UNMAPPED",
    mappingReason: "INTENTIONALLY_UNMAPPED",
    displayMappingState: "INTENTIONALLY_UNMAPPED",
    matchedRuleCount: 0,
    canonicalSalesUnitId: null,
    canonicalDisplayName: null,
    reasonNote: "브랜드 캠페인",
    reasonNoteInherited: true,
  },
  {
    rowNo: 3,
    campaignId: "cmp-1003",
    campaignName: "0403_모바일피드_러닝",
    adType: "성과형DA",
    adStatus: "집행중",
    weekdayLabel: "금요일",
    totalCost: 60000,
    mappingStatus: "UNMAPPED",
    mappingReason: "MULTIPLE_RULE_MATCHES",
    displayMappingState: "UNMAPPED",
    matchedRuleCount: 2,
    canonicalSalesUnitId: null,
    canonicalDisplayName: null,
    reasonNote: null,
    reasonNoteInherited: false,
  },
];

export const mockCostSettings: CostSettingListItem[] = [
  {
    id: "cost-1",
    storeId: "store-main",
    canonicalSalesUnitId: "sales-unit-1",
    canonicalDisplayName: "러닝모자 / 블랙",
    unitCost: 4500,
    feeRate: 0.035,
    otherCost: 500,
    appliedOrderItemCount: 12,
    canEdit: false,
    canClose: true,
    canDeactivate: false,
    blockingReason: "ALREADY_APPLIED",
    effectiveFrom: "2026-03-01",
    effectiveTo: null,
    isActive: true,
  },
  {
    id: "cost-2",
    storeId: "store-main",
    canonicalSalesUnitId: "sales-unit-2",
    canonicalDisplayName: "두줄 무릎 보호대 / 모던그레이",
    unitCost: 10000,
    feeRate: 0.034,
    otherCost: 400,
    appliedOrderItemCount: 8,
    canEdit: false,
    canClose: true,
    canDeactivate: false,
    blockingReason: "ALREADY_APPLIED",
    effectiveFrom: "2026-03-15",
    effectiveTo: null,
    isActive: true,
  },
  {
    id: "cost-3",
    storeId: "store-main",
    canonicalSalesUnitId: "sales-unit-3",
    canonicalDisplayName: "트레이닝 양말 / 화이트",
    unitCost: 0,
    feeRate: null,
    otherCost: 0,
    appliedOrderItemCount: 0,
    canEdit: true,
    canClose: false,
    canDeactivate: true,
    blockingReason: null,
    effectiveFrom: "2026-04-05",
    effectiveTo: null,
    isActive: true,
  },
];

export const mockOperations: OperationListItem[] = [
  {
    operationId: "operation-1",
    operationType: "ORDER_SYNC",
    status: "SUCCEEDED",
    createdAt: "2026-04-02T10:00:00+09:00",
    startedAt: "2026-04-02T10:00:01+09:00",
    finishedAt: "2026-04-02T10:01:12+09:00",
    cutoffAt: "2026-04-02T10:00:00+09:00",
    errorMessage: null,
  },
  {
    operationId: "operation-2",
    operationType: "AD_UPLOAD_CONFIRM",
    status: "QUEUED",
    createdAt: "2026-04-03T09:20:00+09:00",
    startedAt: null,
    finishedAt: null,
    cutoffAt: "2026-04-03T09:20:00+09:00",
    errorMessage: null,
  },
  {
    operationId: "operation-3",
    operationType: "RECALCULATE_AD_MAPPING",
    status: "RUNNING",
    createdAt: "2026-04-03T08:10:00+09:00",
    startedAt: "2026-04-03T08:10:01+09:00",
    finishedAt: null,
    cutoffAt: "2026-04-03T08:10:00+09:00",
    errorMessage: null,
  },
  {
    operationId: "operation-4",
    operationType: "RECALCULATE_ORDER_MAPPING",
    status: "FAILED",
    createdAt: "2026-04-01T16:00:00+09:00",
    startedAt: "2026-04-01T16:00:01+09:00",
    finishedAt: "2026-04-01T16:04:20+09:00",
    cutoffAt: "2026-04-01T16:00:00+09:00",
    errorMessage: "source signature 1건 재계산 중 FK 검증 실패",
  },
];

export const mockOperationDetail: OperationDetail = {
  operationId: "operation-1",
  storeId: "store-main",
  operationType: "ORDER_SYNC",
  status: "SUCCEEDED",
  cutoffAt: "2026-04-02T10:00:00+09:00",
  createdAt: "2026-04-02T10:00:00+09:00",
  startedAt: "2026-04-02T10:00:01+09:00",
  finishedAt: "2026-04-02T10:01:12+09:00",
  errorMessage: null,
  requestSummary: {
    dateFrom: "2026-03-04",
    dateTo: "2026-04-02",
    rangeMode: "MANUAL",
  },
  resultSummary: {
    ordersUpserted: 128,
    orderItemsUpserted: 191,
    orderSourceSignaturesCreated: 7,
    unknownOrderStatusCount: 1,
    paymentDateMissingCount: 2,
  },
};

export const mockUnmappedSummary: UnmappedSummary = {
  unmappedOrderItemCount: 12,
  unmappedOrderRevenue: 92000,
  conflictOrderItemCount: 2,
  conflictOrderRevenue: 44000,
  unmappedCampaignCount: 3,
  unmappedAdCost: 60000,
  conflictCampaignCount: 1,
  conflictAdCost: 18000,
  intentionalUnmappedCampaignCount: 1,
  intentionalUnmappedAdCost: 23200,
};

export const mockProfitDetailPreview: ProfitDetailPreview = {
  displayName: "러닝모자 / 블랙",
  orderCount: 15,
  adCampaignCount: 4,
  deliveryFeeReferenceTotal: 12000,
  fallbackFeeCostPortion: 1022.5,
  profitStatus: "COMPLETE",
};
